### ISSUE TITLE
Contributing Guide Missing

### ISSUE THREAD

**Issue by Hard-Coder05** [appwrite/playground-for-flutter#10]
The Contribution Guide for this repo is missing!

**Comment by Hard-Coder05** [comment]
I am working on this issue!

**Comment by rsrinath14** [comment]
issue #7 
I have already raised an issue and made a PR regarding this previously

**Comment by eldadfux** [comment]
Hey @Hard-Coder05 you've done a good job on #11, but most of the content you added is already in the appwrite/appwrite contribution guide and it will be very hard to keep the list of tutorials/videos up-to-date + we have about ~6 playground for lots of other languages 😔

It could be a nice idea to add to the core project contribution guide a small section with a link to the appwrite/awesome-appwrite repo that has links to multiple Appwrite related resources.
