### ISSUE TITLE
The main.dart is too long

### ISSUE THREAD

**Issue by nayakastha** [appwrite/playground-for-flutter#12]
Decluttering this file will be a good way to may the documentation good

Also, I would like to work on this issue.

**Comment by eldadfux** [comment]
I think it's essential for the goal of this repo (keep it simple) is to keep all the examples in a single file.

Maybe we can reduce the amount of examples to make it a bit shorter.

**Comment by piedcipher** [comment]
Seperation would be better. Easy for anyone to checkout desired example.

Also `then` syntax is odd. `async-await` & `FutureBuilder` should be used instead of doing things in `initState`.

**Comment by piedcipher** [comment]
It's nice to break the issues. What do you think folks?

**Comment by nayakastha** [comment]
Issues as in?

**Comment by piedcipher** [comment]
- Seperating the examples.
- Refactoring to `async-await`.
- Refactoring to FutureBuilder.

**Comment by piedcipher** [comment]
Issues as in separate GitHub issues. We can break it down into 3 issues.

**Comment by nayakastha** [comment]
Yeah got it! Dividing would make it easier to address the issues.

**Comment by piedcipher** [comment]
@eldadfux I would appreciate your inputs or directions on this. Thanks.

**Comment by nayakastha** [comment]
Since there is no response, I guess I will be closing this issue
