### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by jkamiphi** [appwrite/playground-for-flutter#24]
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         5,2s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try
using Jetifier to solve the incompatibility.
Building plugin device_info_plus...
Exception: The plugin device_info_plus could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by lohanidamodar** [comment]
@jkamiphi Please help us by providing more information
1. `flutter doctor`
2. Also try by first `flutter clean` and then trying to build
Thank you

**Comment by lohanidamodar** [comment]
Closing as there was no further response. Feel free to re-open if the issues persist.
Thank you
