### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/playground-for-flutter#27]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by divshacker** [comment]
Please assign this to me 
Thank you

**Comment by JubayerJoy** [comment]
Hi @Meldiron, @TorstenDittmann, Did a similar task before, interested to work on it if available.
Cheers.

**Comment by christyjacob4** [comment]
@divshacker  @JubayerJoy  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by siddhiiguptaa** [comment]
Hello @christyjacob4 I am beginner but this looks good to me. I would love to get my hands on this and provide the solution you're looking for.

**Comment by Meldiron** [comment]
@siddhiiguptaa Assigned it to you! All the best 🚀

**Comment by atishay1743** [comment]
@christyjacob4 can I work on this one?

**Comment by Meldiron** [comment]
@atishay1743  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Meldiron** [comment]
@siddhiiguptaa Hey there, hope you are doing well 👋
Could you please confirm with us you are working on this issue? As always, you can join us on [Discord](https://appwrite.io/discord) if you need any help.

**Comment by siddhiiguptaa** [comment]
> @siddhiiguptaa Hey there, hope you are doing well 👋 Could you please confirm with us you are working on this issue? As always, you can join us on [Discord](https://appwrite.io/discord) if you need any help.

Hello! Sorry for the late reply, but this issue has already been completed. I forgot yo link my PR with this issue though. 😅

**Comment by siddhiiguptaa** [comment]
#28 Here is the link!

**Comment by Meldiron** [comment]
@siddhiiguptaa Awesome, thanks for the PR! 🥳 Please give us some time to review it.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
