### ISSUE TITLE
OAuth for Google

### ISSUE THREAD

**Issue by 5stones1sling** [appwrite/playground-for-flutter#33]
What am I suppose to fill in the Google settings in web console?

What is App id and app secret?

**Comment by ignertic** [comment]
Please read the documentation at [appwrite.io/docs](https://appwrite.io/docs)

**Comment by stnguyen90** [comment]
@kennedykok, those are the values from Google when setting up OAuth authentication. The Appwrite Console now has a link to [Google's Docs](https://support.google.com/googleapi/answer/6158849) for setting up OAuth. 

![image](https://user-images.githubusercontent.com/1477010/210869219-20de82f1-22dd-48f0-adcc-e6f8d2e739e7.png)
