### ISSUE TITLE
Screen Shot of the Examples 

### ISSUE THREAD

**Issue by rsrinath14** [appwrite/playground-for-flutter#6]
It would be great to have screen shots of the app in the README section.
I would be happy to work on it if nobody claims.

**Comment by aryanA101a** [comment]
I'll do it @srinath1412001

**Comment by rsrinath14** [comment]
Hey @aryanfluxion,
Let the maintainers confirm if they really want that change. Proceed after that.
Have a good day!

**Comment by eldadfux** [comment]
Sorry for the late response, PR merged.
